<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:localhealthcarecompany="http://LHCBpelService.asose.disim.univaq.it/"
	xmlns:properties="http://RegistryOfficeBpelService.asose.disim.univaq.it/properties"
	xmlns:tns="http://RegistryOfficeBpelService.asose.disim.univaq.it/propertiesAliases"
	xmlns:user="http://UserBpelService.asose.disim.univaq.it/"
	xmlns:veterinary="http://VeterinaryBpelService.asose.disim.univaq.it/"
	xmlns:registry="http://RegistryOfficeBpelService.asose.disim.univaq.it/"
	xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	name="propertiesAliases" targetNamespace="http://RegistryOfficeBpelService.asose.disim.univaq.it/propertiesAliases">
	
	<import location="LHCBpel.wsdl"
		namespace="http://LHCBpelService.asose.disim.univaq.it/" />
		
	<import location="UserBpel.wsdl"
		namespace="http://UserBpelService.asose.disim.univaq.it/" />
		
	<import location="VeterinaryBpel.wsdl" 
		namespace="http://VeterinaryBpelService.asose.disim.univaq.it/"/>
	
	<import location="RegistryOfficeBpel.wsdl" namespace="http://RegistryOfficeBpelService.asose.disim.univaq.it/"/>
		
	<vprop:propertyAlias
		messageType="localhealthcarecompany:farmBusinessStartupRequest"
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
			
	<vprop:propertyAlias
		messageType="localhealthcarecompany:farmSiteInspectionResponse"
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
	
	<vprop:propertyAlias
		messageType="localhealthcarecompany:farmRegistrationNotification"
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
	
	<vprop:propertyAlias messageType="user:farmBusinessStartupResponse"
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
	
	<vprop:propertyAlias messageType="veterinary:farmRegistrationNotification" 
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
	
	<vprop:propertyAlias messageType="veterinary:farmSiteInspectionRequest" 
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
	
	<vprop:propertyAlias messageType="registry:farmOpeningNotification" 
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
	
</definitions>
