<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:localhealthcarecompany="http://eu.chorevolution.farmbusinessstartup/localhealthcarecompany"
	xmlns:properties="http://RegistryOfficeBpelService.bpd.disim.univaq.it/properties"
	xmlns:tns="http://RegistryOfficeBpelService.bpd.disim.univaq.it/propertiesAliases"
	xmlns:user="http://eu.chorevolution.farmbusinessstartup/user"
	xmlns:veterinary="http://eu.chorevolution.farmbusinessstartup/veterinary"
	xmlns:registry="http://RegistryOfficeBpelService.bpd.disim.univaq.it/"
	xmlns:vprop="http://docs.oasis-open.org/wsbpel/2.0/varprop" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	name="propertiesAliases" targetNamespace="http://RegistryOfficeBpelService.bpd.disim.univaq.it/propertiesAliases">
	
	<import location="LocalHealthcareCompany.wsdl"
		namespace="http://eu.chorevolution.farmbusinessstartup/localhealthcarecompany" />
		

		
	<import location="Veterinary.wsdl" 
		namespace="http://eu.chorevolution.farmbusinessstartup/veterinary"/>
	
	<import location="RegistryOfficeBpel.wsdl" namespace="http://RegistryOfficeBpelService.bpd.disim.univaq.it/"/>
		
	<vprop:propertyAlias
		messageType="localhealthcarecompany:farmBusinessStartupRequest"
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
			
	<vprop:propertyAlias
		messageType="localhealthcarecompany:farmSiteInspectionResponse"
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
	
	<vprop:propertyAlias
		messageType="localhealthcarecompany:farmRegistrationNotification"
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
	
	<vprop:propertyAlias messageType="User:farmBusinessStartupResponse"
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
	
	<vprop:propertyAlias messageType="veterinary:farmRegistrationNotification" 
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
	
	<vprop:propertyAlias messageType="veterinary:farmSiteInspectionRequest" 
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
	
	<vprop:propertyAlias messageType="registry:farmOpeningNotification" 
		part="parameters" propertyName="properties:ChoreographyID">
		<vprop:query>ChoreographyID</vprop:query>
	</vprop:propertyAlias>
	
</definitions>
