<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:cduser="http://eu.chorevolution.farmbusinessstartup/cduser" xmlns:localhealthcarecompany="http://eu.chorevolution.farmbusinessstartup/cdlocalhealthcarecompany" xmlns:municipality="http://eu.chorevolution.farmbusinessstartup/services/municipality" xmlns:registryoffice="http://eu.chorevolution.farmbusinessstartup/cdregistryoffice" xmlns:tns="http://eu.chorevolution.farmbusinessstartup/userArtifacts" xmlns:veterinary="http://eu.chorevolution.farmbusinessstartup/cdveterinary" xmlns:veterinaryregionalregister="http://eu.chorevolution.farmbusinessstartup/services/veterinaryregionalregister" targetNamespace="http://eu.chorevolution.farmbusinessstartup/userArtifacts">
  <import location="cdUser.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/cduser"/>
  <import location="localhealthcarecompany.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/cdlocalhealthcarecompany"/>
  <import location="municipality.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/services/municipality"/>
  <import location="registryoffice.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/cdregistryoffice"/>
  <import location="veterinary.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/cdveterinary"/>
  <import location="veterinaryregionalregister.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/services/veterinaryregionalregister"/>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="CDLocalHealthcareCompanyUserPTPLT">
    <role name="LocalHealthcareCompanyUserPTRole" portType="cduser:LocalHealthcareCompanyUserPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="CDUserPTPLT">
    <role name="UserPTRole" portType="cduser:UserPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="RegistryOfficeLocalHealthcareCompanyPTPLT">
    <role name="RegistryOfficeLocalHealthcareCompanyPTRole" portType="localhealthcarecompany:RegistryOfficeLocalHealthcareCompanyPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="UserLocalHealthcareCompanyPTPLT">
    <role name="UserLocalHealthcareCompanyPTRole" portType="localhealthcarecompany:UserLocalHealthcareCompanyPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="VeterinaryLocalHealthcareCompanyPTPLT">
    <role name="VeterinaryLocalHealthcareCompanyPTRole" portType="localhealthcarecompany:VeterinaryLocalHealthcareCompanyPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="MunicipalityPTPLT">
    <role name="MunicipalityPTRole" portType="municipality:MunicipalityPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="LocalHealthcareCompanyRegistryOfficePTPLT">
    <role name="LocalHealthcareCompanyRegistryOfficePTRole" portType="registryoffice:LocalHealthcareCompanyRegistryOfficePT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="LocalHealthcareCompanyVeterinaryPTPLT">
    <role name="LocalHealthcareCompanyVeterinaryPTRole" portType="veterinary:LocalHealthcareCompanyVeterinaryPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="RegistryOfficeVeterinaryPTPLT">
    <role name="RegistryOfficeVeterinaryPTRole" portType="veterinary:RegistryOfficeVeterinaryPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="VeterinaryRegionalRegisterPTPLT">
    <role name="VeterinaryRegionalRegisterPTRole" portType="veterinaryregionalregister:VeterinaryRegionalRegisterPT"/>
  </partnerLinkType>
</definitions>
