<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" 
			xmlns:veterinaryBPEL="http://it.univaq.disim.bpd.VeterinaryBPEL" 
			xmlns:localhealthcarecompany="http://eu.chorevolution.farmbusinessstartup/localhealthcarecompany" 
			xmlns:registryoffice="http://eu.chorevolution.farmbusinessstartup/cdregistryoffice" 
			xmlns:local="http://it.univaq.disim.bpd.VeterinaryBPELArtifacts" 
			xmlns:veterinary="http://eu.chorevolution.farmbusinessstartup/veterinary" 
			targetNamespace="http://it.univaq.disim.bpd.VeterinaryBPELArtifacts">
			
  <import location="VeterinaryBPEL.wsdl" namespace="http://it.univaq.disim.bpd.VeterinaryBPEL"/>
  <import location="localhealthcarecompany.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/localhealthcarecompany"/>
  <import location="cdRegistryOffice.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/cdregistryoffice"/>
  <import location="Veterinary.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/veterinary"/>
  
  
	<!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
		Michele Intrevado Gianluca Rea
		 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
		 
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="LocalHealthcareCompanyVeterinary">
    <role name="LocalHealthcareCompanyVeterinaryRole" portType="veterinaryBPEL:LocalHealthcareCompanyVeterinary"/>
  </partnerLinkType> <!--  --> 
  
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="RegistryOfficeVeterinary">
    <role name="RegistryOfficeVeterinaryRole" portType="veterinaryBPEL:RegistryOfficeVeterinary"/>
  </partnerLinkType> <!--  --> 
  
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="VeterinaryLocalHealthcareCompany">
    <role name="VeterinaryLocalHealthcareCompanyRole" portType="localhealthcarecompany:LocalHealthcareCompanyPort"/>
  </partnerLinkType> <!--  --> 
  
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="Veterinary">
    <role name="VeterinaryRole" portType="veterinary:VeterinaryPT"/>
  </partnerLinkType>  <!--  -->
  
</definitions>
