<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:cdveterinary="http://eu.chorevolution.farmbusinessstartup/cdveterinary" xmlns:localhealthcarecompany="http://eu.chorevolution.farmbusinessstartup/cdlocalhealthcarecompany" xmlns:municipality="http://eu.chorevolution.farmbusinessstartup/services/municipality" xmlns:registryoffice="http://eu.chorevolution.farmbusinessstartup/cdregistryoffice" xmlns:tns="http://eu.chorevolution.farmbusinessstartup/veterinaryArtifacts" xmlns:user="http://eu.chorevolution.farmbusinessstartup/cduser" xmlns:veterinary="http://eu.chorevolution.farmbusinessstartup/veterinary" xmlns:veterinaryregionalregister="http://eu.chorevolution.farmbusinessstartup/services/veterinaryregionalregister" targetNamespace="http://eu.chorevolution.farmbusinessstartup/veterinaryArtifacts">
  <import location="cdVeterinary.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/cdveterinary"/>
  <import location="localhealthcarecompany.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/cdlocalhealthcarecompany"/>
  <import location="user.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/cduser"/>
  <import location="municipality.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/services/municipality"/>
  <import location="registryoffice.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/cdregistryoffice"/>
  <import location="veterinary.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/veterinary"/>
  <import location="veterinaryregionalregister.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/services/veterinaryregionalregister"/>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="CDLocalHealthcareCompanyVeterinaryPTPLT">
    <role name="LocalHealthcareCompanyVeterinaryPTRole" portType="cdveterinary:LocalHealthcareCompanyVeterinaryPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="CDRegistryOfficeVeterinaryPTPLT">
    <role name="RegistryOfficeVeterinaryPTRole" portType="cdveterinary:RegistryOfficeVeterinaryPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="RegistryOfficeLocalHealthcareCompanyPTPLT">
    <role name="RegistryOfficeLocalHealthcareCompanyPTRole" portType="localhealthcarecompany:RegistryOfficeLocalHealthcareCompanyPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="UserLocalHealthcareCompanyPTPLT">
    <role name="UserLocalHealthcareCompanyPTRole" portType="localhealthcarecompany:UserLocalHealthcareCompanyPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="VeterinaryLocalHealthcareCompanyPTPLT">
    <role name="VeterinaryLocalHealthcareCompanyPTRole" portType="localhealthcarecompany:VeterinaryLocalHealthcareCompanyPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="LocalHealthcareCompanyUserPTPLT">
    <role name="LocalHealthcareCompanyUserPTRole" portType="user:LocalHealthcareCompanyUserPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="UserPTPLT">
    <role name="UserPTRole" portType="user:UserPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="MunicipalityPTPLT">
    <role name="MunicipalityPTRole" portType="municipality:MunicipalityPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="LocalHealthcareCompanyRegistryOfficePTPLT">
    <role name="LocalHealthcareCompanyRegistryOfficePTRole" portType="registryoffice:LocalHealthcareCompanyRegistryOfficePT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="VeterinaryPTPLT">
    <role name="VeterinaryPTRole" portType="veterinary:VeterinaryPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="VeterinaryRegionalRegisterPTPLT">
    <role name="VeterinaryRegionalRegisterPTRole" portType="veterinaryregionalregister:VeterinaryRegionalRegisterPT"/>
  </partnerLinkType>
</definitions>
