<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:cdregistryoffice="http://eu.chorevolution.farmbusinessstartup/cdregistryoffice" xmlns:localhealthcarecompany="http://eu.chorevolution.farmbusinessstartup/cdlocalhealthcarecompany" xmlns:municipality="http://eu.chorevolution.farmbusinessstartup/services/municipality" xmlns:registryoffice="http://eu.chorevolution.farmbusinessstartup/registryoffice" xmlns:tns="http://eu.chorevolution.farmbusinessstartup/registryofficeArtifacts" xmlns:user="http://eu.chorevolution.farmbusinessstartup/cduser" xmlns:veterinary="http://eu.chorevolution.farmbusinessstartup/cdveterinary" xmlns:veterinaryregionalregister="http://eu.chorevolution.farmbusinessstartup/services/veterinaryregionalregister" targetNamespace="http://eu.chorevolution.farmbusinessstartup/registryofficeArtifacts">
  <import location="cdRegistryOffice.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/cdregistryoffice"/>
  <import location="localhealthcarecompany.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/cdlocalhealthcarecompany"/>
  <import location="user.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/cduser"/>
  <import location="municipality.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/services/municipality"/>
  <import location="veterinary.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/cdveterinary"/>
  <import location="registryoffice.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/registryoffice"/>
  <import location="veterinaryregionalregister.wsdl" namespace="http://eu.chorevolution.farmbusinessstartup/services/veterinaryregionalregister"/>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="CDLocalHealthcareCompanyRegistryOfficePTPLT">
    <role name="LocalHealthcareCompanyRegistryOfficePTRole" portType="cdregistryoffice:LocalHealthcareCompanyRegistryOfficePT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="RegistryOfficeLocalHealthcareCompanyPTPLT">
    <role name="RegistryOfficeLocalHealthcareCompanyPTRole" portType="localhealthcarecompany:RegistryOfficeLocalHealthcareCompanyPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="UserLocalHealthcareCompanyPTPLT">
    <role name="UserLocalHealthcareCompanyPTRole" portType="localhealthcarecompany:UserLocalHealthcareCompanyPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="VeterinaryLocalHealthcareCompanyPTPLT">
    <role name="VeterinaryLocalHealthcareCompanyPTRole" portType="localhealthcarecompany:VeterinaryLocalHealthcareCompanyPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="LocalHealthcareCompanyUserPTPLT">
    <role name="LocalHealthcareCompanyUserPTRole" portType="user:LocalHealthcareCompanyUserPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="UserPTPLT">
    <role name="UserPTRole" portType="user:UserPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="MunicipalityPTPLT">
    <role name="MunicipalityPTRole" portType="municipality:MunicipalityPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="LocalHealthcareCompanyVeterinaryPTPLT">
    <role name="LocalHealthcareCompanyVeterinaryPTRole" portType="veterinary:LocalHealthcareCompanyVeterinaryPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="RegistryOfficeVeterinaryPTPLT">
    <role name="RegistryOfficeVeterinaryPTRole" portType="veterinary:RegistryOfficeVeterinaryPT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="RegistryOfficePTPLT">
    <role name="RegistryOfficePTRole" portType="registryoffice:RegistryOfficePT"/>
  </partnerLinkType>
  <partnerLinkType xmlns="http://docs.oasis-open.org/wsbpel/2.0/plnktype" name="VeterinaryRegionalRegisterPTPLT">
    <role name="VeterinaryRegionalRegisterPTRole" portType="veterinaryregionalregister:VeterinaryRegionalRegisterPT"/>
  </partnerLinkType>
</definitions>
